### ISSUE TITLE
Issues with Python 3.13

### ISSUE THREAD

**Issue by rdong8** [bitcoindevkit/bdk-ffi#633]
**Describe the bug**  

Running the example fails with Python 3.13.

**To Reproduce**  

```python
import bdkpython as bdk


descriptor = bdk.Descriptor("wpkh(tprv8ZgxMBicQKsPcx5nBGsR63Pe8KnRUqmbJNENAfGftF3yuXoMMoVJJcYeUw5eVkm9WBPjWYt6HMWYJNesB5HaNVBaFc1M6dRjWSYnmewUMYy/84h/0h/0h/0/*)", bdk.Network.TESTNET)
db_config = bdk.DatabaseConfig.MEMORY()
blockchain_config = bdk.BlockchainConfig.ELECTRUM(
    bdk.ElectrumConfig(
        url = "ssl://electrum.blockstream.info:60002",
        socks5 = None,
        retry = 5,
        timeout = None,
        stop_gap = 100,
        validate_domain = True,
    )
)
blockchain = bdk.Blockchain(blockchain_config)

wallet = bdk.Wallet(
             descriptor=descriptor,
             change_descriptor=None,
             network=bdk.Network.TESTNET,
             database_config=db_config,
         )

# print new receive address
address_info = wallet.get_address(bdk.AddressIndex.LAST_UNUSED())
address = address_info.address
index = address_info.index
print(f"New BIP84 testnet address: {address} at index {index}")


# print wallet balance
wallet.sync(blockchain, None)
balance = wallet.get_balance()
print(f"Wallet balance is: {balance.total}")
```

**Expected behavior**  

Example works as expected. What actually happens:

```
Traceback (most recent call last):
  File "/tmp/tmp/main.py", line 1, in <module>
    import bdkpython as bdk
  File "/tmp/tmp/.venv/lib64/python3.13/site-packages/bdkpython/__init__.py", line 1, in <module>
    from bdkpython.bdk import *
  File "/tmp/tmp/.venv/lib64/python3.13/site-packages/bdkpython/bdk.py", line 346, in <module>
    _UniFFILib = loadIndirect()
  File "/tmp/tmp/.venv/lib64/python3.13/site-packages/bdkpython/bdk.py", line 341, in loadIndirect
    return ctypes.cdll.LoadLibrary(path)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/ctypes/__init__.py", line 471, in LoadLibrary
    return self._dlltype(name)
           ~~~~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/ctypes/__init__.py", line 390, in __init__
    self._handle = _dlopen(self._name, mode)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
OSError: /tmp/tmp/.venv/lib64/python3.13/site-packages/bdkpython/libbdkffi.so: cannot open shared object file: No such file or directory
```

**Build environment**  
 - BDK tag/commit:  0.32.0 Python package
 - OS+version:    Fedora 41
 - Rust/Cargo version:  N/A
 - Rust/Cargo target:    N/A

**Additional context**  
 

Switching to Python 3.12 fixes the error. Was not able to test the 1.0.0* beta packages since they don't seem to be available yet.

```bash
uv pip install bdkpython==1.0.0b5

  × No solution found when resolving dependencies:
  ╰─▶ Because bdkpython==1.0.0b5 has no wheels with a matching Python ABI tag and you require bdkpython==1.0.0b5, we can conclude that your requirements are
      unsatisfiable.
```

**Comment by thunderbiscuit** [comment]
Hey thanks for reporting! I'm not a Python expert but I've seen these types of issues pop up and I think we should be able to find a way to make this work for you.

1. I suspect the issue with the 1.0.0 beta 5 dependency (and I highly recommend you work with the 1.0 releases at this point) is that you are developing on a platform we currently have not built a wheel for (but one of our current wheels probably works! the naming of the wheel is creating the problem). You're on Fedora + Python 3.13? I'll need to take a look, let me know if that's not correct. You can take a look at [the wheels we have here](https://pypi.org/project/bdkpython/1.0.0b5/#files).
2. For the 0.32 release, we did not build a wheel for Python 3.13, so I suspect that's where the issue comes from. Your codeblock runs for me and prints the correct balance for this descriptor on Python 3.11. [Our releases for 0.32 cover 3.8 to 3.12](https://pypi.org/project/bdkpython/0.32.0/#files).

Let me know if attempting the example works for you when using a lower Python version!

**Comment by thunderbiscuit** [comment]
At this point it probably is a good idea to start supporting 3.13 even though it's fairly new (and maybe deprecate some of the older versions?). If you work with Python on a daily basis and have opinions on this let me know what you think.
